services:
  mediacms-migrations:
    image: mediacms/mediacms:7.2.0
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: 'password'
      REDIS_LOCATION: redis://mediacms-redis:6379/1
      POSTGRES_HOST: mediacms-db
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      mediacms-redis:
        condition: service_healthy
      mediacms-db:
        condition: service_healthy
  mediacms-web:
    image: mediacms/mediacms:7.2.0
    ports:
      - "8440:80"
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      REDIS_LOCATION: redis://mediacms-redis:6379/1
      POSTGRES_HOST: mediacms-db
    restart: always
    depends_on:
      - mediacms-migrations
  mediacms-celery-beat:
    image: mediacms/mediacms:7.2.0
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      REDIS_LOCATION: redis://mediacms-redis:6379/1
      POSTGRES_HOST: mediacms-db
    depends_on:
      - mediacms-redis
  mediacms-celery-worker:
    image: mediacms/mediacms:7.2.0
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
      REDIS_LOCATION: redis://mediacms-redis:6379/1
      POSTGRES_HOST: mediacms-db
    depends_on:
      - mediacms-migrations
  mediacms-db:
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: America/New_York
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
  mediacms-redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data:
  media_store:
