apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediacms-celery-beat
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediacms-celery-beat
  template:
    metadata:
      labels:
        app: mediacms-celery-beat
    spec:
      containers:
        - name: celery-beat
          image: "mediacms/mediacms:{{ .Values.mediacms_version }}"
          env:
            - name: ENABLE_UWSGI
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_CELERY_SHORT
              value: "no"
            - name: ENABLE_CELERY_LONG
              value: "no"
            - name: ENABLE_MIGRATIONS
              value: "no"
            - name: FRONTEND_HOST
              value: "mediacms.{{ .Values.domain }}"
            - name: REDIS_LOCATION
              value: redis://mediacms-redis:6379/1
            - name: POSTGRES_HOST
              value: mediacms-db
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mediacms-secret-key
                  key: SECRET_KEY
