apiVersion: batch/v1
kind: Job
metadata:
  name: mediacms-migrations
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: mediacms-migrations
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mediacms-migrations
          image: "mediacms/mediacms:{{ .Values.mediacms_version }}"
          args:
            - "./deploy/docker/prestart.sh"
          env:
            - name: ENABLE_UWSGI
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_CELERY_SHORT
              value: "no"
            - name: ENABLE_CELERY_LONG
              value: "no"
            - name: ENABLE_CELERY_BEAT
              value: "no"
            - name: ADMIN_USER
              value: "admin"
            - name: ADMIN_EMAIL
              value: "admin@localhost"
            - name: ADMIN_PASSWORD
              value: "password"
            - name: FRONTEND_HOST
              value: "mediacms.{{ .Values.domain }}"
            - name: REDIS_LOCATION
              value: redis://mediacms-redis:6379/1
            - name: POSTGRES_HOST
              value: mediacms-db
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mediacms-secret-key
                  key: SECRET_KEY
