apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediacms-celery-worker
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediacms-celery-worker
  template:
    metadata:
      labels:
        app: mediacms-celery-worker
    spec:
      containers:
        - name: celery-worker
          image: "mediacms/mediacms:{{ .Values.mediacms_version }}"
          env:
            - name: ENABLE_UWSGI
              value: "no"
            - name: ENABLE_NGINX
              value: "no"
            - name: ENABLE_CELERY_BEAT
              value: "no"
            - name: ENABLE_MIGRATIONS
              value: "no"
            - name: FRONTEND_HOST
              value: "mediacms.{{ .Values.domain }}"
            - name: REDIS_LOCATION
              value: redis://mediacms-redis:6379/1
            - name: POSTGRES_HOST
              value: mediacms-db
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mediacms-secret-key
                  key: SECRET_KEY
          volumeMounts:
            - name: mediacms-media-store
              mountPath: /home/mediacms.io/mediacms/media_files/
      volumes:
        - name: mediacms-media-store
          persistentVolumeClaim:
            claimName: mediacms-media-store
