apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediacms-postgres-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: longhorn-static
  volumeName: mediacms-postgres-data
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediacms-db
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediacms-db
  template:
    metadata:
      labels:
        app: mediacms-db
    spec:
      containers:
        - name: postgres
          image: postgres:17.2-alpine
          env:
            - name: POSTGRES_USER
              value: mediacms
            - name: POSTGRES_PASSWORD
              value: mediacms
            - name: POSTGRES_DB
              value: mediacms
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: mediacms-postgres-data
              mountPath: /var/lib/postgresql
          livenessProbe:
            exec:
              command: ["pg_isready", "-d", "mediacms", "-U", "mediacms"]
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: mediacms-postgres-data
          persistentVolumeClaim:
            claimName: mediacms-postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: mediacms-db
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mediacms-db
  ports:
    - port: 5432
