# global encryption key for Longhorn volumes. PVs created from the Longhorn UI
# ("Create PV/PVC" on a volume with the "Encrypted" checkbox) reference this
# Secret by its default name "longhorn-crypto" in "longhorn-system"
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "longhorn-crypto"
  namespace: "longhorn-system"
stringData:
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_VALUE: "{{ secrets.longhorn.global_encryption_secret_crypto_key }}"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"
