- name: Add repository
  kubernetes.core.helm_repository:
    repo_name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Install
  kubernetes.core.helm:
    chart_ref: metallb/metallb
    chart_version: 0.14.7
    release_name: metallb
    release_namespace: metallb-system
    create_namespace: true
    update_repo_cache: true
