- name: Add repository
  kubernetes.core.helm_repository:
    repo_name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Install
  kubernetes.core.helm:
    chart_ref: metallb/metallb
    chart_version: 0.14.7
    release_name: metallb
    release_namespace: metallb-system
    create_namespace: true
    update_repo_cache: true

- name: Create configuration objects
  vars:
    metallb_address_pool: "{{ global_vars.metallb_address_pool }}"
  kubernetes.core.k8s:
    state: present
    template:
      - path: templates/ip-address-pool.yaml
      - path: templates/l2-advertisement.yaml
