- name: Add repository
  kubernetes.core.helm_repository:
    repo_name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    chart_version: 1.7.0
    release_name: longhorn
    release_namespace: longhorn-system
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('ansible.builtin.template', 'templates/values.yaml') | from_yaml }}"
