- name: "Configure CephFS volumes"
  include_tasks: "configure-volume.yaml"
  loop:
    - "mediacms_media_store"
    - "mediacms_postgresql_data"
    - "photoprism_originals"
    - "photoprism_storage"
    - "photoprism_import"
  loop_control:
    loop_var: "ceph_volume"
