environment_name: prod
secrets:
  k3s:
    token: |-
      aaaaaaaaaaBBBBBBBBBBcccccccccc111111111133333333335555555555DDDDDDD::server:aaaaabbbbb11111222224444499999dd
  tailscale:
    tailnet_dns_name: "dog-snake.ts.net"
  tailscale_operator:
    oauth:
      client_id: abCDE1234aaaBBBBB
      client_secret: tskey-client-abCDE1234aaaBBBBB-aaaaaBBBBBccccc111112222299999999
  mediacms:
    secret_key: "kdZdSfNsKUP5*XC+uoI8nVrba7CEvV67&az(BYkaHIe-5WscTf"
