environment_name: "prod"
secrets:
  tailscale:
    domain_name: "dog-snake.ts.net"
    oauth_client_key: "aaaaaaaaabbbbbbbb"
    oauth_client_secret: "tskey-client-zzzzzzzzzzzzzzzzz-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  mediacms:
    secret_key: "aaaaaaa!!!!!!!(((((((()))))))))^^^^^^^^^1111111111"
    admin_password: "password"
    postgres_password: "postgres"
