- name: Check current k3s version
  block:
    - name: Check if k3s is installed
      ansible.builtin.stat:
        path: "{{ k3s_bin_path }}"
      changed_when: false
      register: k3s_binary

    - name: Check k3s version
      when: k3s_binary.stat.exists
      ansible.builtin.shell:
        cmd: "{{ k3s_bin_path }} --version"
      changed_when: false
      register: installed_k3s_version

- name: Install or upgrade k3s
  when: ( not k3s_binary.stat.exists ) or ( k3s_version not in installed_k3s_version.stdout )
  block:
    - name: Download k3s installer
      ansible.builtin.get_url:
        url: "https://get.k3s.io"
        dest: "/tmp/k3s-install.sh"
        mode: '755'
      register: k3s_installer_script

    - name: Build environment variables for k3s installer
      ansible.builtin.set_fact:
        k3s_env_var_assignments: >-
          {%- for var_assignment in k3s_installer_vars -%}
          {%- for key, value in var_assignment.items() -%}
          {{ key }}={{ value }}
          {% endfor -%}
          {%- endfor -%}

    - name: Run k3s installer
      become: true
      ansible.builtin.shell:
        cmd: >
          {{ k3s_env_var_assignments }}
          {{ k3s_installer_script.dest }}
          --token "{{ k3s.token }}"
