# see: https://hub.docker.com/r/mediacms/mediacms/tags
mediacms_version: 7.2.0

# DNS suffix that the mediacms-web Ingress will be exposed under. mediacms uses it to populate URLs and such
domain: "zonkey-moth.ts.net"

# TODO
secret_key: "ma!s3^b-cw!f#7s6s0m3*jx77a@riw(7701**(r=ww%w!2+yk2"
