services:
  mediacms-tailscale:
    image: "tailscale/tailscale:stable"
    hostname: "mediacms"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file: ".env"
    volumes:
      - "/opt/homelab/mediacms/tailscale_state:/var/lib/tailscale"
      - "/dev/net/tun:/dev/net/tun"
    networks:
      - mediacms_internal

  mediacms-migrations:
    image: "mediacms/mediacms:{{ docker_compose.mediacms_version }}"
    env_file: ".env"
    environment:
      ENABLE_UWSGI: "no"
      ENABLE_NGINX: "no"
      ENABLE_CELERY_SHORT: "no"
      ENABLE_CELERY_LONG: "no"
      ENABLE_CELERY_BEAT: "no"
      FRONTEND_HOST: "mediacms.{{ secrets.tailscale.domain_name }}"
      REDIS_LOCATION: "redis://mediacms-redis:6379/1"
      POSTGRES_HOST: "mediacms-db"
    command: "./deploy/docker/prestart.sh"
    restart: "on-failure"
    depends_on:
      mediacms-redis:
        condition: "service_healthy"
      mediacms-db:
        condition: "service_healthy"
    networks:
      - mediacms_internal

  mediacms-web:
    image: "mediacms/mediacms:{{ docker_compose.mediacms_version }}"
    network_mode: "service:mediacms-tailscale"
    env_file: ".env"
    volumes:
      - "/opt/homelab/mediacms/media_store:/home/mediacms.io/mediacms/media_files/"
    environment:
      ENABLE_CELERY_BEAT: "no"
      ENABLE_CELERY_SHORT: "no"
      ENABLE_CELERY_LONG: "no"
      ENABLE_MIGRATIONS: "no"
      FRONTEND_HOST: "mediacms.{{ secrets.tailscale.domain_name }}"
      REDIS_LOCATION: "redis://mediacms-redis:6379/1"
      POSTGRES_HOST: "mediacms-db"
    restart: "always"
    depends_on:
      - "mediacms-migrations"
      - "mediacms-tailscale"

  mediacms-celery-beat:
    image: "mediacms/mediacms:{{ docker_compose.mediacms_version }}"
    env_file: ".env"
    environment:
      ENABLE_UWSGI: "no"
      ENABLE_NGINX: "no"
      ENABLE_CELERY_SHORT: "no"
      ENABLE_CELERY_LONG: "no"
      ENABLE_MIGRATIONS: "no"
      FRONTEND_HOST: "mediacms.{{ secrets.tailscale.domain_name }}"
      REDIS_LOCATION: "redis://mediacms-redis:6379/1"
      POSTGRES_HOST: "mediacms-db"
    depends_on:
      - "mediacms-redis"
    networks:
      - mediacms_internal

  mediacms-celery-worker:
    image: "mediacms/mediacms:{{ docker_compose.mediacms_version }}"
    env_file: ".env"
    volumes:
      - "/opt/homelab/mediacms/media_store:/home/mediacms.io/mediacms/media_files/"
    environment:
      ENABLE_UWSGI: "no"
      ENABLE_NGINX: "no"
      ENABLE_CELERY_BEAT: "no"
      ENABLE_MIGRATIONS: "no"
      FRONTEND_HOST: "mediacms.{{ secrets.tailscale.domain_name }}"
      REDIS_LOCATION: "redis://mediacms-redis:6379/1"
      POSTGRES_HOST: "mediacms-db"
    depends_on:
      - "mediacms-migrations"
    networks:
      - mediacms_internal

  mediacms-db:
    image: "postgres:17.2-alpine"
    env_file: ".env"
    volumes:
      - "/opt/homelab/mediacms/postgres_data:/var/lib/postgresql/data/"
    restart: "always"
    environment:
      TZ: "America/New_York"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: "30s"
      timeout: "10s"
      retries: 5
    networks:
      - mediacms_internal

  mediacms-redis:
    image: "redis:alpine"
    restart: "always"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: "30s"
      timeout: "10s"
      retries: 3
    networks:
      - mediacms_internal

networks:
  mediacms_internal:
