apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ jellyfin_config_pvc_name }}"
  namespace: "jellyfin"
spec:
  storageClassName: "longhorn-static"
  volumeName: "jellyfin-config"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
