# see:
#   https://docs.k3s.io/helm
#   https://github.com/traefik/traefik-helm-chart/blob/9861b3dc46ca46609966d6edf9708b8c50d5ee44/traefik/values.yaml#L793
#   https://metallb.io/usage/#requesting-specific-ips

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      annotations:
        metallb.io/loadBalancerIPs: {{ ip_address }}
