---
ungrouped:
  hosts:
    localhost:
      ansible_connection: local

k3s_servers:
  hosts:
    carly:
      # TODO add info for longhorn label and annotation
      ansible_host: carly.home
      ansible_user: jvilla
      k3s_installer_vars:
        - INSTALL_K3S_EXEC: server
      k3s_cmd_line_args:
        - --disable
        - servicelb
