- hosts: all
  tasks:
    - name: Load vault
      ansible.builtin.include_vars:
        file: vault/vault.yaml

    # to save typing, the 'environment_name' variable is read from the vault
    - name: Include global variables
      ansible.builtin.include_vars:
        file: "{{ environment_name }}.yaml"

- hosts: k3s_servers
  roles:
    - k3s

# TODO need to label and annotate nodes somewhere

- hosts: localhost
  roles:
    - helm_metallb
    - helm_longhorn
