collections:
  - name: ansible.utils
    type: galaxy
    version: ">=6.0.0,<7.0.0"
  - name: community.general
    type: galaxy
    version: ">=12.5.0,<13.0.0"
  - name: kubernetes.core
    type: galaxy
    version: ">=6.3.0,<7.0.0"
